### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by bntzio** [fabiospampinato/vscode-no-unsupported#1]
The extension is not working, vscode version 1.16.1.

**Comment by fabiospampinato** [comment]
It does work for me, and I'm using v1.16.1, under macOS.

Perhaps it doesn't work under other OSs, which one are you running?

**Comment by bntzio** [comment]
Mm... That's weird, macOS as well, I'm going to try it later with a fresh install to see what happens.

**Comment by fabiospampinato** [comment]
Alright. Btw this extension patches the file under "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js", if it still doesn't work for you, having a copy of that file would help find the problem.

**Comment by justnealpatel** [comment]
@fabiospampinato what do you mean by having a copy? Having a copy of the patched file?

**Comment by fabiospampinato** [comment]
@justnealpatel I mean I need a copy of that file to know why it doesn't get patched properly. "patched" or "unpatched" shouldn't really make any difference if this extension doesn't work for you.

**Comment by justnealpatel** [comment]
Ah, I see. Another option I tried to do was just putting my css inside workbench.main.css, but that also caused the Unsupported issue.

**Comment by fabiospampinato** [comment]
Yes, they must be checking some hashes or something. 

If you'd send me the aforementioned I think I could fix this.

**Comment by justnealpatel** [comment]
That's what it seems like. And definitely! Do you just want me to send workbench.main.js or what?
Will put my `workbench.main.css, workbench.main.js` in a zip.

[Workbench.zip](https://github.com/fabiospampinato/vscode-no-unsupported/files/1564411/Workbench.zip)

**Comment by fabiospampinato** [comment]
@justnealpatel that file looks pretty much like mine, it should get patched properly. There must be a problem with writing it or something. What OS are you using? Under Windows VSC must be running with administrator priviledges.

@bntzio and @justnealpatel can you try again with the new v1.0.8?

**Comment by justnealpatel** [comment]
Still getting the same error. I'm running macOS 10.12.6. Is the extension working for you? @fabiospampinato 
It has also left the Unsupported part on my window even after I've uninstalled vscode-no-unsupported and the CSS and JS loader extensions.

**Comment by fabiospampinato** [comment]
@justnealpatel yes, it does work for me.

What error are you getting exactly? 

You should have actually disabled the css and js loader before uninstalling it (it provides a specific command for doing that) if you wanted to remove the "Unsupported" text.

**Comment by justnealpatel** [comment]
Not sure of the exact error, just know that the title still appends [Unsupported]. Is there a way to debug it within vscode?

**Comment by fabiospampinato** [comment]
@justnealpatel Yes, you should fork the extension, put a `debugger` statement right about [here](https://github.com/fabiospampinato/vscode-no-unsupported/blob/master/src/patch.ts#L19), launch a  debug session, run "Unsupported: Remove" from the newly opened VSC window and check what goes wrong, maybe the path to the `workbench.main.js` file is not right, maybe the regex used for patching it doesn't match, or something else. Let me know what you find 👍

**Comment by cbengtson85** [comment]
This wasn't working for me either (MacOS Sierra), I'm using the custom css extension and have added this to a custom javascript file which has solved the problem 😄 

```
setTimeout(function () {
    var targetNode = document.getElementsByClassName("window-title")[0];
    var config = { childList: true };

    var callback = function(mutationsList) {
        for(var mutation of mutationsList) {
            if (mutation.type == 'childList') {
                var text = targetNode.innerHTML;
                if(text.indexOf('Unsupported') > -1)
                	targetNode.innerHTML = text.replace('[Unsupported]', '');
            }
        }
    };

    var observer = new MutationObserver(callback);

    observer.observe(targetNode, config);


}, 3000);


```

**Comment by fabiospampinato** [comment]
@cbengtson85 that's a decent workaround, thanks for sharing.

Unfortunately I have no idea why this extension doesn't work on your systems, it would be great if you guys had the time to debug this.

**Comment by valleybay** [comment]
I'm also having some issues with this.
It works in the beginning, when I start up VSCode, or if I do a `Reload Window`. I'm on OS X 10.13.1, and VSCode 1.21.1

**Comment by fabiospampinato** [comment]
@valleybay it take as a bit before `[Unsupported]` is actually rendered, I don't think this extension is working at all for you if you're still seeing it.

As I said I've no idea why this isn't working for you guys, I can't reproduce it in my system.

Refer to [this comment](https://github.com/fabiospampinato/vscode-no-unsupported/issues/1#issuecomment-353467638) if you'd like to help.

**Comment by valleybay** [comment]
I went with the javascript fix @cbengtson85 provided, as it feels even cleaner than using a separate extension for the matter.

Thanks, though! :-)

**Comment by fabiospampinato** [comment]
@valleybay on the other end this extension doesn't affect performance at all and it works (when it works) immediately, without needing to remove `[Unsupported]` every 3 seconds like that snippet does.

**Comment by valleybay** [comment]
@fabiospampinato Do you think it's a notable performance hit though? I don't know much about Electron.

**Comment by fabiospampinato** [comment]
@valleybay actually I've misread the code, using `setTimeout` and `MutationObserver` I don't think you're going to notice any delay, and the performance hit should be minimal.

**Comment by reka18** [comment]
Nice that you guys are discussing solving this obnoxious bug, but why don't the VS Code devs fix it in the editor itself without the community haven't to develop a patch? Why do we have to deal with this at all?

**Comment by fabiospampinato** [comment]
@data83 A while ago I asked them for an option for removing it https://github.com/Microsoft/vscode/issues/30556.

**Comment by fabiospampinato** [comment]
This extension is deprecated, please switch to this one: https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums
