### ISSUE TITLE
It doesn't seem to work with vscode september update

### ISSUE THREAD

**Issue by codeams** [fabiospampinato/vscode-no-unsupported#2]
I had the extension working like a charm for the last 3-4 months but after the update it's no longer working.

I follow the steps to remove the "[Unsupported]" from the title. Everything seems to be fine but after the reload it's still there.

![oct-08-2018 17-41-42](https://user-images.githubusercontent.com/5368213/46637372-8c1efb00-cb21-11e8-8b4f-8a36277ee80c.gif)

**Comment by fabiospampinato** [comment]
This extension is deprecated, you should use this instead: https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums 

I've just tried and it works.
